name: CI

on: [push]

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: mulle-sde/github-ci@v1
      env: 
       MULLE_SDE_GITHUB_CI_VENDOR: ${{ secrets.MULLE_SDE_GITHUB_CI_VENDOR }}
      if: env.MULLE_SDE_GITHUB_CI_VENDOR = "" || env.MULLE_SDE_GITHUB_CI_VENDOR = "mulle-sde"
       
    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Build Environment
      run:  env

    - name: Mulle-SDE Fetch
      run: mulle-sde fetch 
      
    - name: Mulle-SDE Craft
      run: mulle-sde craft --${BUILD_TYPE:-release}

    - name: Mulle-SDE Test
      run: mulle-sde test
      
